# Usa versão LTS do Node
FROM node:25-alpine

# Define diretório de trabalho
WORKDIR /app

# Copia arquivos de dependência
COPY package*.json ./

# Instala dependências
# npm ci é mais rápido e confiável porque usa o package-lock.json
RUN npm ci

# Copia restante da aplicação
COPY . .

# Documenta a porta usada
EXPOSE 3000

# Comando para iniciar em modo desenvolvimento
# geralmente usando nodemon
CMD ["npm", "run", "dev"]